### ISSUE TITLE
TA comments on milestone 3 [First Pass]

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/DSCI_532_group-106_R_supermarket#10]
Hello,

Thanks for your milestone 3 submission. Everything looks good except for some issues I am listing below,
- You have to provide a teamwork contract for project 2 and put a link to it in the readme.
- In your proposal you have to describe each research question. Also, you provided one research question. Is that the only question you are trying to answer by the app?
- When doing a pull request try to summarize the tasks that you changed in the pull request description.
- For your app visualization, you were supposed to show screenshots of at least your ggplot2 or plotly plots and code. Check milestone 3.
- It is always a good idea to provide a good and concise description of your app at the beginning of the app page.

I may give you more detailed feedback on Friday. Ensure that you commit often.

Thanks!

**Comment by reikookamoto** [comment]
@hsmohammed,

I would like to clarify certain parts of the submission on behalf of my team. I believe that the comments we received are not reflective of our submitted work.

This is ***exactly*** what was stated on `milestone3.md`: 

In your milestone3 repo on GitHub.ubc.ca, this week you will submit:

- Updated (if necessary) team contract
- A README file that contains links to the following items:
  - Group project repo for DashR project on GitHub.com
  - Code of conduct file
  - LICENSE file
  - GitHub.com project README
  - Contributing.md if you chose to list it as a separate file, otherwise as part of the GitHub.com project README
  - Reflections (details below)
- ONE screenshot of your current progress on creating your plots in R (see below for a screenshot)

With respect to the team contract and screenshot, if you take a look at each team member's milestone3 repo, you will find the files directly uploaded there. Moreover, the links to these files are included in the `README.md` of each team member's milestone 3 repo. Please click [here](https://github.ubc.ca/mds-2019-20/DSCI_532_milestone3_rokamoto) to see my milestone3 repo, as an example. 

With respect to the pull requests, in the comments section, we've summarized the things that were changed. Please click on any of the following pull requests to view these summaries:  #1, #2 , #4, #5.

Finally with respect to the dashboard description, please refer to the description section of the `README.md` section of this repo. 

I hope you take these comments into consideration and grade us accordingly.

Thank you.

**Comment by hsmohammed** [comment]
Hi @reikookamoto 
Thank you for your reply and clarifications. I have seen your teamwork contract in everyone's personal repos. That looks fine, sorry I missed that. Regarding the pull request, I see you provide description of each one, but what I meant is to be specific about the changes as other team members may miss what already has been modified and that may create conflicts.
Regarding the description in the app page, I mean I the sketch you have to show the space in which you will provide a description and a user's guide for using the app.

Please let me know if my other comments/suggestions are not clear. 

Thank you, I always encourage you to discuss any comments that I provide.
