### ISSUE TITLE
Barplots 

### ISSUE THREAD

**Issue by reikookamoto** [UBC-MDS/DSCI_532_group-106_R_supermarket#12]
- I think it's redundant to include a legend next to each barplot. Is it possible to just include a legend for each shift? 
- Change "Average Satisfaction" to "Average Customer Satisfaction" 
- Include guiding example for second tab

**Comment by moniquewong** [comment]
Adding to this, in the code:
- Refactor into snake case instead of camel case
- Lots of redundant code to make the plots (each plot is a separate function?); can probably refactor this to follow DRY principle

**Comment by clsu22** [comment]
Yes, I also think my code is redundant, but I have tried to leave only one legend for all bar plots, but unfortunately my effort didn't work. I'll try to fix it if possible. 

Another issue happened is that when I only use one function and called it several times to make plots, the y-axis title looks weird, it read as "y_title" for tooltip instead of the name I set before. That's why I write redundant codes here. I'll also try to fix it if possible.
